language: R


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install: [
        "sudo add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ xenial main\" -y",
        "sudo apt-get update -q",
        "sudo apt-get install libfreetype6"
      ]
      install: Rscript -e 'install.packages(c("testthat", "vdiffr"))'
      script:
        - Rscript Tools/requiredPackages.R JASP-Engine/JASP/R true
        - Rscript Tools/showVersion.R
        - cd JASP-Tests/R/tests/
        - R < testthat.R --no-save
    - r: "3.3"
