language: r
cache: packages
sudo: required
os: osx
osx_image: xcode9.1
brew_packages: cairo
install: Rscript -e 'install.packages(c("testthat", "vdiffr"))'
script:
  - Rscript Tools/requiredPackages.R JASP-Engine/JASP/R true
  - cd JASP-Tests/R/tests/
  - R < testthat.R --no-save