language: R
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      addons: { apt: {sources: debian-sid, packages: libfreetype6}}
    - os: linux
      dist: trusty
      sudo: required
      before_install: [
        "sudo add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ xenial main\" -y",
        "sudo apt-get update -q",
        "sudo apt-get install libfreetype6"
      ]
    - r: devel
    - os: osx
      osx_image: xcode7.2
      brew_packages: cairo
      latex: false
