language: R
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install: [
        "sudo add-apt-repository \"deb http://archive.ubuntu.com/ubuntu/ xenial main\" -y",
        "sudo apt-get update -q",
        "sudo apt-get install libfreetype6"
      ]
      install: Rscript -e 'install.packages(c("testthat", "vdiffr"))'
      script:
        - Rscript Tools/requiredPackages.R JASP-Engine/JASP/R true
        - Rscript -e 'cat("\nCairo version: ");gdtools::version_cairo();cat("\nFreetype version: ");gdtools::version_freetype();cat("\nFontconfig version: ");gdtools::version_fontconfig()'
        - cd JASP-Tests/R/tests/
        - R < testthat.R --no-save
